# Generated by Django 4.2.1 on 2023-06-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
